; Tilemap layout, in tiles
DEF TILEMAP_WIDTH  EQU 16
DEF TILEMAP_HEIGHT EQU 16
DEF TILEMAP_TOP    EQU 1
DEF TILEMAP_LEFT   EQU 2
DEF ATTRMAP_WIDTH  EQU 20
DEF ATTRMAP_HEIGHT EQU 18

; Number of frames in the animation
DEF MAX_ANIMATION_FRAMES EQU 6
